language: android
sudo: false
notifications:
  email: false

before_install:
  - yes | sdkmanager "platforms;android-28"

script: ./CI/travis.sh

android:
  components:
    - tools
    - build-tools-28.0.3
    - platform-tools
    - tools
    - android-28
